version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3004:3004"
    volumes:
      - ./frontend:/app
      
# not sure i need this file